In pandas there is a frame work name DataFrames . These are used for making tabular data . It is a combination of rows and colume . this frame work offers many function for data manuplation operations

In [3]:
import numpy as np
import pandas as pd 
from numpy.random import randn

In [17]:
tab = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = ['W','X','Y','Z'])
print(tab)

          W         X         Y         Z
A  0.893917 -0.643932  0.347588 -1.577657
B -0.452788 -0.934273 -1.019127  0.885435
C  0.802632 -1.945086 -0.932768  1.483057
D -0.697100 -1.130255  0.844680 -0.622825
E -1.257134 -1.052704 -0.186097 -0.538737

In [15]:
tab['W']

A    0.355852
B   -0.363847
C    0.513565
D    0.842529
E   -0.990891
Name: W, dtype: float64

In [16]:
tab[['W','X']]

          W         X
A  0.355852  1.925830
B -0.363847 -0.741238
C  0.513565 -2.305308
D  0.842529 -0.753443
E -0.990891 -1.387729

In [17]:
type(tab)

pandas.core.frame.DataFrame

In [18]:
tab['New'] = tab['W'] + tab['X']

In [19]:
print(tab)

          W         X         Y         Z       New
A  0.355852  1.925830 -2.101493 -1.775623  2.281681
B -0.363847 -0.741238 -0.564706  1.220567 -1.105085
C  0.513565 -2.305308 -0.115852 -1.279615 -1.791743
D  0.842529 -0.753443 -1.102246 -0.077265  0.089087
E -0.990891 -1.387729  0.344346 -1.193712 -2.378620

Using this drop command "New" Column will not delete permanatly .For Deleting Col permanatly we should use impluse attribute .

In [21]:
tab.drop('New',axis=1)

          W         X         Y         Z
A  0.355852  1.925830 -2.101493 -1.775623
B -0.363847 -0.741238 -0.564706  1.220567
C  0.513565 -2.305308 -0.115852 -1.279615
D  0.842529 -0.753443 -1.102246 -0.077265
E -0.990891 -1.387729  0.344346 -1.193712

In [22]:
print(tab)

          W         X         Y         Z       New
A  0.355852  1.925830 -2.101493 -1.775623  2.281681
B -0.363847 -0.741238 -0.564706  1.220567 -1.105085
C  0.513565 -2.305308 -0.115852 -1.279615 -1.791743
D  0.842529 -0.753443 -1.102246 -0.077265  0.089087
E -0.990891 -1.387729  0.344346 -1.193712 -2.378620

In [26]:
tab.drop('New',axis =1 , inplace= True)

In [27]:
print(tab)

          W         X         Y         Z
A  0.355852  1.925830 -2.101493 -1.775623
B -0.363847 -0.741238 -0.564706  1.220567
C  0.513565 -2.305308 -0.115852 -1.279615
D  0.842529 -0.753443 -1.102246 -0.077265
E -0.990891 -1.387729  0.344346 -1.193712

By using loc indexing method we can access row

In [32]:
tab.loc['A']

W    0.355852
X    1.925830
Y   -2.101493
Z   -1.775623
Name: A, dtype: float64

By using iloc indexing method we can access row by interger notation

In [33]:
tab.iloc[0]

W    0.355852
X    1.925830
Y   -2.101493
Z   -1.775623
Name: A, dtype: float64

In [34]:
tab.loc[['A','B'] , ['W','X']]

          W         X
A  0.355852  1.925830
B -0.363847 -0.741238

In [35]:
tab.loc[['A','B']]

          W         X         Y         Z
A  0.355852  1.925830 -2.101493 -1.775623
B -0.363847 -0.741238 -0.564706  1.220567

Conditional Selection

In [2]:
import numpy as np 
import pandas as pd 
from numpy.random import randn

In [4]:
df = pd.DataFrame(randn(5,5) , index = ' A B C D E'.split() , columns = 'V W X Y Z'.split())

In [5]:
print(df)

          V         W         X         Y         Z
A -0.300942  0.733973  0.113082 -0.763447  0.334885
B -0.358610 -0.668597  1.480161  0.364830 -0.107143
C  1.211171  0.083799 -0.341377 -0.832752  1.996974
D -0.940958 -0.519126  0.162285 -0.148133  0.392869
E -0.086077  0.815754  0.700063 -1.249291  0.251557

In [6]:
df

          V         W         X         Y         Z
A -0.300942  0.733973  0.113082 -0.763447  0.334885
B -0.358610 -0.668597  1.480161  0.364830 -0.107143
C  1.211171  0.083799 -0.341377 -0.832752  1.996974
D -0.940958 -0.519126  0.162285 -0.148133  0.392869
E -0.086077  0.815754  0.700063 -1.249291  0.251557

In [8]:
df['V'] > 0

A    False
B    False
C     True
D    False
E    False
Name: V, dtype: bool

In [10]:
result = df['W']>0

In [11]:
result

A     True
B    False
C     True
D    False
E     True
Name: W, dtype: bool

In [12]:
df > 0

       V      W      X      Y      Z
A  False   True   True  False   True
B  False  False   True   True  False
C   True   True  False  False   True
D  False  False   True  False   True
E  False   True   True  False   True

In [13]:
df

          V         W         X         Y         Z
A -0.300942  0.733973  0.113082 -0.763447  0.334885
B -0.358610 -0.668597  1.480161  0.364830 -0.107143
C  1.211171  0.083799 -0.341377 -0.832752  1.996974
D -0.940958 -0.519126  0.162285 -0.148133  0.392869
E -0.086077  0.815754  0.700063 -1.249291  0.251557

In [14]:
df[df['W']>0]

          V         W         X         Y         Z
A -0.300942  0.733973  0.113082 -0.763447  0.334885
C  1.211171  0.083799 -0.341377 -0.832752  1.996974
E -0.086077  0.815754  0.700063 -1.249291  0.251557

In [17]:
df[df['X']<0]['Z']

C    1.996974
Name: Z, dtype: float64

In [20]:
df[df['W']<0][['Y','Z']]

          Y         Z
B  0.364830 -0.107143
D -0.148133  0.392869

CONDITION => & or |

In [21]:
df

          V         W         X         Y         Z
A -0.300942  0.733973  0.113082 -0.763447  0.334885
B -0.358610 -0.668597  1.480161  0.364830 -0.107143
C  1.211171  0.083799 -0.341377 -0.832752  1.996974
D -0.940958 -0.519126  0.162285 -0.148133  0.392869
E -0.086077  0.815754  0.700063 -1.249291  0.251557

In [23]:
df[(df['W']>0) & (df['Y']>0)]

Empty DataFrame
Columns: [V, W, X, Y, Z]
Index: []

In [24]:
df[(df['W']>0 ) | (df['Y'] >0 )]

          V         W         X         Y         Z
A -0.300942  0.733973  0.113082 -0.763447  0.334885
B -0.358610 -0.668597  1.480161  0.364830 -0.107143
C  1.211171  0.083799 -0.341377 -0.832752  1.996974
E -0.086077  0.815754  0.700063 -1.249291  0.251557

Some Advance Topic in indexing

If we want to reset the indexing then we using reset_index() function. 
Using reset_index function , the index will start from 0,1,2,3,4......n . 
If we want to save permanant we use inplace attribute .

In [27]:
temp = df 
print(temp)

          V         W         X         Y         Z
A -0.300942  0.733973  0.113082 -0.763447  0.334885
B -0.358610 -0.668597  1.480161  0.364830 -0.107143
C  1.211171  0.083799 -0.341377 -0.832752  1.996974
D -0.940958 -0.519126  0.162285 -0.148133  0.392869
E -0.086077  0.815754  0.700063 -1.249291  0.251557

In [28]:
temp.reset_index()

  index         V         W         X         Y         Z
0     A -0.300942  0.733973  0.113082 -0.763447  0.334885
1     B -0.358610 -0.668597  1.480161  0.364830 -0.107143
2     C  1.211171  0.083799 -0.341377 -0.832752  1.996974
3     D -0.940958 -0.519126  0.162285 -0.148133  0.392869
4     E -0.086077  0.815754  0.700063 -1.249291  0.251557

In [29]:
temp

          V         W         X         Y         Z
A -0.300942  0.733973  0.113082 -0.763447  0.334885
B -0.358610 -0.668597  1.480161  0.364830 -0.107143
C  1.211171  0.083799 -0.341377 -0.832752  1.996974
D -0.940958 -0.519126  0.162285 -0.148133  0.392869
E -0.086077  0.815754  0.700063 -1.249291  0.251557

In [31]:
temp.reset_index(inplace=True)

In [32]:
temp

  index         V         W         X         Y         Z
0     A -0.300942  0.733973  0.113082 -0.763447  0.334885
1     B -0.358610 -0.668597  1.480161  0.364830 -0.107143
2     C  1.211171  0.083799 -0.341377 -0.832752  1.996974
3     D -0.940958 -0.519126  0.162285 -0.148133  0.392869
4     E -0.086077  0.815754  0.700063 -1.249291  0.251557

In [33]:
temp

  index         V         W         X         Y         Z
0     A -0.300942  0.733973  0.113082 -0.763447  0.334885
1     B -0.358610 -0.668597  1.480161  0.364830 -0.107143
2     C  1.211171  0.083799 -0.341377 -0.832752  1.996974
3     D -0.940958 -0.519126  0.162285 -0.148133  0.392869
4     E -0.086077  0.815754  0.700063 -1.249291  0.251557

In [34]:
newind = 'CA NY WY OR CO'.split()

In [36]:
df['T'] = newind
df

  index         V         W         X         Y         Z New   T
0     A -0.300942  0.733973  0.113082 -0.763447  0.334885  CA  CA
1     B -0.358610 -0.668597  1.480161  0.364830 -0.107143  NY  NY
2     C  1.211171  0.083799 -0.341377 -0.832752  1.996974  WY  WY
3     D -0.940958 -0.519126  0.162285 -0.148133  0.392869  OR  OR
4     E -0.086077  0.815754  0.700063 -1.249291  0.251557  CO  CO

In [37]:
df.set_index('New')

    index         V         W         X         Y         Z   T
New
CA      A -0.300942  0.733973  0.113082 -0.763447  0.334885  CA
NY      B -0.358610 -0.668597  1.480161  0.364830 -0.107143  NY
WY      C  1.211171  0.083799 -0.341377 -0.832752  1.996974  WY
OR      D -0.940958 -0.519126  0.162285 -0.148133  0.392869  OR
CO      E -0.086077  0.815754  0.700063 -1.249291  0.251557  CO

In [38]:
df

  index         V         W         X         Y         Z New   T
0     A -0.300942  0.733973  0.113082 -0.763447  0.334885  CA  CA
1     B -0.358610 -0.668597  1.480161  0.364830 -0.107143  NY  NY
2     C  1.211171  0.083799 -0.341377 -0.832752  1.996974  WY  WY
3     D -0.940958 -0.519126  0.162285 -0.148133  0.392869  OR  OR
4     E -0.086077  0.815754  0.700063 -1.249291  0.251557  CO  CO