In pandas there is a frame work name DataFrames . These are used for making tabular data . It is a combination of rows and colume . this frame work offers many function for data manuplation operations

In [3]:
import numpy as np
import pandas as pd 
from numpy.random import randn

In [13]:
tab = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = ['W','X','Y','Z'])
print(tab)

          W         X         Y         Z
A  0.355852  1.925830 -2.101493 -1.775623
B -0.363847 -0.741238 -0.564706  1.220567
C  0.513565 -2.305308 -0.115852 -1.279615
D  0.842529 -0.753443 -1.102246 -0.077265
E -0.990891 -1.387729  0.344346 -1.193712

In [15]:
tab['W']

A    0.355852
B   -0.363847
C    0.513565
D    0.842529
E   -0.990891
Name: W, dtype: float64

In [16]:
tab[['W','X']]

          W         X
A  0.355852  1.925830
B -0.363847 -0.741238
C  0.513565 -2.305308
D  0.842529 -0.753443
E -0.990891 -1.387729

In [17]:
type(tab)

pandas.core.frame.DataFrame

In [18]:
tab['New'] = tab['W'] + tab['X']

In [19]:
print(tab)

          W         X         Y         Z       New
A  0.355852  1.925830 -2.101493 -1.775623  2.281681
B -0.363847 -0.741238 -0.564706  1.220567 -1.105085
C  0.513565 -2.305308 -0.115852 -1.279615 -1.791743
D  0.842529 -0.753443 -1.102246 -0.077265  0.089087
E -0.990891 -1.387729  0.344346 -1.193712 -2.378620

Using this drop command "New" Column will not delete permanatly .For Deleting Col permanatly we should use impluse attribute .

In [21]:
tab.drop('New',axis=1)

          W         X         Y         Z
A  0.355852  1.925830 -2.101493 -1.775623
B -0.363847 -0.741238 -0.564706  1.220567
C  0.513565 -2.305308 -0.115852 -1.279615
D  0.842529 -0.753443 -1.102246 -0.077265
E -0.990891 -1.387729  0.344346 -1.193712

In [22]:
print(tab)

          W         X         Y         Z       New
A  0.355852  1.925830 -2.101493 -1.775623  2.281681
B -0.363847 -0.741238 -0.564706  1.220567 -1.105085
C  0.513565 -2.305308 -0.115852 -1.279615 -1.791743
D  0.842529 -0.753443 -1.102246 -0.077265  0.089087
E -0.990891 -1.387729  0.344346 -1.193712 -2.378620

In [26]:
tab.drop('New',axis =1 , inplace= True)

In [27]:
print(tab)

          W         X         Y         Z
A  0.355852  1.925830 -2.101493 -1.775623
B -0.363847 -0.741238 -0.564706  1.220567
C  0.513565 -2.305308 -0.115852 -1.279615
D  0.842529 -0.753443 -1.102246 -0.077265
E -0.990891 -1.387729  0.344346 -1.193712

By using loc indexing method we can access row

In [32]:
tab.loc['A']

W    0.355852
X    1.925830
Y   -2.101493
Z   -1.775623
Name: A, dtype: float64

By using iloc indexing method we can access row by interger notation

In [33]:
tab.iloc[0]

W    0.355852
X    1.925830
Y   -2.101493
Z   -1.775623
Name: A, dtype: float64

In [34]:
tab.loc[['A','B'] , ['W','X']]

          W         X
A  0.355852  1.925830
B -0.363847 -0.741238

In [35]:
tab.loc[['A','B']]

          W         X         Y         Z
A  0.355852  1.925830 -2.101493 -1.775623
B -0.363847 -0.741238 -0.564706  1.220567