In [1]:
import numpy as np 
import pandas as pd

In [2]:
d = { 'A': [0,np.nan , 2] , 'B' : [0,1,2] , 'C':[2,np.nan , np.nan]}

In [3]:
print(d)

{'A': [0, nan, 2], 'B': [0, 1, 2], 'C': [2, nan, nan]}

In [5]:
df = pd.DataFrame(d)
df

     A  B    C
0  0.0  0  2.0
1  NaN  1  NaN
2  2.0  2  NaN

If dropna() function is depend on axis if axis = 0 then it will work according to row .
If there is any Null or missing value in a row then the whole row will be removed 
When axis = 1 , then it will work according to column . If there is any null or missing value in the 
col then whole col will not consider

In [7]:
df.dropna()

     A  B    C
0  0.0  0  2.0

In [1]:
df.dropna(axis=1)

NameError: name 'df' is not defined

In [2]:
import numpy as np 
import pandas as pd

In [3]:
d = { 'A': [0,np.nan , 2] , 'B' : [0,1,2] , 'C':[2,np.nan , np.nan]}

In [4]:
df = pd.DataFrame(d)

In [6]:
df.dropna(thresh=3)

     A  B    C
0  0.0  0  2.0

In [7]:
df.fillna(value = 10)

      A  B     C
0   0.0  0   2.0
1  10.0  1  10.0
2   2.0  2  10.0

In [8]:
df

     A  B    C
0  0.0  0  2.0
1  NaN  1  NaN
2  2.0  2  NaN

In [9]:
df['A'].fillna(value=5)

0    0.0
1    5.0
2    2.0
Name: A, dtype: float64